services:
  app:
    image: tactigon-sdk
    build:
      context: .  
    network_mode: "host"
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - .:/app
    stdin_open: true  
    tty: true        