services:
  tactigon:
    container_name: Tactigon-SDK
    build:
      context: .  
    network_mode: "host"
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - .:/app
    stdin_open: true  
    tty: true        