version: '3'
services:
  app:
    container_name: Tactigon-Test
    build:
      context: .  
    network_mode: "host"
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true  
    tty: true        
    restart: always   
    command: "python examples/gesture/app.py"